server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Collect logs from Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    
    relabel_configs:
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      
      # Extract container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
      
      # Extract container image
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      
      # Only scrape SIGame containers
      - source_labels: ['__meta_docker_container_name']
        regex: '.*(sigame|postgres|redis|kafka|minio).*'
        action: keep
      
      # Determine service from container name
      - source_labels: ['__meta_docker_container_name']
        regex: '.*sigame-auth-service.*'
        target_label: 'service'
        replacement: 'auth'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*sigame-lobby-service.*'
        target_label: 'service'
        replacement: 'lobby'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*sigame-game-service.*'
        target_label: 'service'
        replacement: 'game'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*sigame-pack-service.*'
        target_label: 'service'
        replacement: 'pack'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*sigame-frontend.*'
        target_label: 'service'
        replacement: 'frontend'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*postgres.*'
        target_label: 'service'
        replacement: 'postgres'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*redis.*'
        target_label: 'service'
        replacement: 'redis'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*kafka.*'
        target_label: 'service'
        replacement: 'kafka'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '.*minio.*'
        target_label: 'service'
        replacement: 'minio'
      
      # Add environment label
      - target_label: 'environment'
        replacement: 'production'
      
      # Add project label
      - target_label: 'project'
        replacement: 'sigame'
    
    # Extract JSON fields from logs
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service_name: service
            message: message
            trace_id: trace_id
            span_id: span_id
      
      # Parse timestamp if present
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - "2006-01-02T15:04:05.000000000Z"
      
      # Add labels from JSON fields
      - labels:
          level:
          service_name:
          trace_id:
      
      # Keep original log line as output
      - output:
          source: message
