#!/bin/bash

# Script to generate proto files for all services

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR/.."

echo "═══════════════════════════════════════════════════════════"
echo "  Generating Proto Files for All Services"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Auth Service (Go)
echo "📦 Auth Service (Go)..."
cd "$ROOT_DIR/services/auth"
bash generate-proto.sh
echo ""

# Game Service (Go)
echo "📦 Game Service (Go)..."
cd "$ROOT_DIR/services/game"
bash generate-proto.sh
echo ""

# Packs Service (Python)
echo "📦 Packs Service (Python)..."
cd "$ROOT_DIR/services/packs"
bash generate-proto.sh
echo ""

# Lobby Service (Kotlin) - generated by Gradle during build
echo "📦 Lobby Service (Kotlin)..."
echo "   Proto files are generated automatically by Gradle during build"
echo "   Run: cd services/lobby && ./gradlew generateProto"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "  ✓ All proto files generated successfully!"
echo "═══════════════════════════════════════════════════════════"

