server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 30s  # Быстрее flush для dev/testing
  complete_block_timeout: 15s
  flush_check_period: 10s

compactor:
  compaction:
    block_retention: 168h  # 7 days

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

query_frontend:
  search:
    max_duration: 0s

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    service_graphs:
      dimensions:
        - http.method
        - http.target
        - http.status_code
    span_metrics:
      dimensions:
        - http.method
        - http.target
        - http.status_code
    local_blocks:
      flush_check_period: 5s
      max_block_duration: 30s
      max_block_bytes: 5242880

overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics
    - local-blocks
