#!/bin/bash

# Auto-generated environment file
# Server IPs from Terraform

cat > .env.production << 'EOF'
# Server IPs
APP_SERVER_IP=89.169.139.21
INFRA_SERVER_IP=10.129.0.26

# PostgreSQL Databases
AUTH_DB_NAME=auth_db
AUTH_DB_USER=authuser
AUTH_DB_PASSWORD=YzRkNmE3ZjNiMjExOGY4ZTQ5NzI1YWNk

LOBBY_DB_NAME=lobby_db
LOBBY_DB_USER=lobbyuser
LOBBY_DB_PASSWORD=NWM4ZGE2YjQzZTcyMWY5ZDgxMzY1YWVi

PACKS_DB_NAME=packs_db
PACKS_DB_USER=packsuser
PACKS_DB_PASSWORD=MGE5ZTRiYzNkNzYxOGY1YTIzNDk3ZGJl

GAME_DB_NAME=game_db
GAME_DB_USER=gameuser
GAME_DB_PASSWORD=NjhiMmQ1ZTlhNGMzMWY3YjU2ODIwOWFk

# Redis
REDIS_HOST=10.129.0.26
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_MAX_MEMORY=512mb

# Kafka
KAFKA_BOOTSTRAP_SERVERS=10.129.0.26:9092

# MinIO
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=ZTM0YzU2ZDhhYmY5MTI3ZDM0NTY4OWFl
MINIO_API_URL=http://10.129.0.26:9000

# JWT
JWT_SECRET=MmU5ZjdkNGJhYzNlMTY4ZjU3MjkzNGRiYTZlOGYxYzNkNGI3ZjlhMmU1YzFkOGY2Mzk0YTdiMmVmOGMxZDU2NA==
JWT_ACCESS_TOKEN_TTL=3600
JWT_REFRESH_TOKEN_TTL=604800

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=YWRtaW4xMjM0NTY3ODkw

# Environment
NODE_ENV=production
GO_ENV=production
PYTHON_ENV=production
GIN_MODE=release

# Logging
DEBUG=false
LOG_LEVEL=info
EOF

echo "✅ .env.production created with server IPs: 89.169.139.21 (app) and 10.129.0.26 (infra)"

