#!/bin/bash

# Quick Deploy Script - Complete automated deployment
# This script automates the entire deployment process

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"

echo "=========================================="
echo "   SIGame Quick Deploy"
echo "=========================================="

# Step 1: Check prerequisites
echo -e "${BLUE}Step 1: Checking prerequisites...${NC}"

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}✗ Terraform not found${NC}"
    echo "Please run: ./deployment/scripts/install-tools.sh"
    exit 1
fi

if ! command -v yc &> /dev/null; then
    echo -e "${RED}✗ Yandex Cloud CLI not found${NC}"
    echo "Please run: ./deployment/scripts/install-tools.sh"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites OK${NC}"

# Step 2: Check Terraform configuration
echo -e "${BLUE}Step 2: Checking Terraform configuration...${NC}"

cd "$PROJECT_ROOT/deployment/terraform"

if [ ! -f "terraform.tfvars" ]; then
    echo -e "${RED}✗ terraform.tfvars not found${NC}"
    echo "Please create it from terraform.tfvars.example and fill in your values"
    exit 1
fi

echo -e "${GREEN}✓ Terraform configuration found${NC}"

# Step 3: Initialize Terraform
echo -e "${BLUE}Step 3: Initializing Terraform...${NC}"
terraform init
echo -e "${GREEN}✓ Terraform initialized${NC}"

# Step 4: Plan infrastructure
echo -e "${BLUE}Step 4: Planning infrastructure...${NC}"
terraform plan -out=tfplan
echo -e "${GREEN}✓ Plan created${NC}"

# Step 5: Confirm deployment
echo ""
echo -e "${YELLOW}Ready to create infrastructure in Yandex Cloud${NC}"
echo -e "${YELLOW}This will create:${NC}"
echo "  - 2 virtual machines (servers)"
echo "  - VPC network and subnets"
echo "  - Security groups"
echo "  - 1 external IP address"
echo ""
read -p "Continue with deployment? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Deployment cancelled"
    exit 0
fi

# Step 6: Apply Terraform
echo -e "${BLUE}Step 6: Creating infrastructure...${NC}"
terraform apply tfplan
echo -e "${GREEN}✓ Infrastructure created${NC}"

# Step 7: Get server IPs
echo -e "${BLUE}Step 7: Getting server information...${NC}"

APP_SERVER_IP=$(terraform output -raw app_server_external_ip)
INFRA_SERVER_IP=$(terraform output -raw infra_server_internal_ip)

echo -e "${GREEN}✓ Servers ready${NC}"
echo "  Application Server: $APP_SERVER_IP"
echo "  Infrastructure Server: $INFRA_SERVER_IP"

# Step 8: Wait for servers to boot
echo -e "${BLUE}Step 8: Waiting for servers to boot (60 seconds)...${NC}"
sleep 60
echo -e "${GREEN}✓ Servers should be ready${NC}"

# Step 9: Update .env.production
echo -e "${BLUE}Step 9: Creating production environment file...${NC}"

cd "$PROJECT_ROOT"

cat > .env.production << EOF
# Generated by quick-deploy.sh on $(date)

# Server IPs
APP_SERVER_IP=$APP_SERVER_IP
INFRA_SERVER_IP=$INFRA_SERVER_IP

# PostgreSQL Databases
AUTH_DB_NAME=auth_db
AUTH_DB_USER=authuser
AUTH_DB_PASSWORD=$(openssl rand -base64 32)

LOBBY_DB_NAME=lobby_db
LOBBY_DB_USER=lobbyuser
LOBBY_DB_PASSWORD=$(openssl rand -base64 32)

PACKS_DB_NAME=packs_db
PACKS_DB_USER=packsuser
PACKS_DB_PASSWORD=$(openssl rand -base64 32)

GAME_DB_NAME=game_db
GAME_DB_USER=gameuser
GAME_DB_PASSWORD=$(openssl rand -base64 32)

# Redis
REDIS_HOST=$INFRA_SERVER_IP
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_MAX_MEMORY=512mb

# Kafka
KAFKA_BOOTSTRAP_SERVERS=$INFRA_SERVER_IP:9092

# MinIO
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$(openssl rand -base64 32)
MINIO_API_URL=http://$INFRA_SERVER_IP:9000

# JWT
JWT_SECRET=$(openssl rand -base64 64)
JWT_ACCESS_TOKEN_TTL=3600
JWT_REFRESH_TOKEN_TTL=604800

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 32)

# Environment
NODE_ENV=production
GO_ENV=production
PYTHON_ENV=production
GIN_MODE=release

# Logging
DEBUG=false
LOG_LEVEL=info
EOF

echo -e "${GREEN}✓ Environment file created${NC}"
echo -e "${YELLOW}IMPORTANT: Save the passwords from .env.production!${NC}"

# Step 10: Copy files to servers
echo -e "${BLUE}Step 10: Copying project files to servers...${NC}"

# Copy to Application Server
echo "Copying to Application Server..."
ssh -o StrictHostKeyChecking=no ubuntu@$APP_SERVER_IP "sudo mkdir -p /opt/sigame && sudo chown ubuntu:ubuntu /opt/sigame"
scp -r $PROJECT_ROOT/* ubuntu@$APP_SERVER_IP:/opt/sigame/
scp .env.production ubuntu@$APP_SERVER_IP:/opt/sigame/

# Copy to Infrastructure Server (via Application Server as jump host)
echo "Copying to Infrastructure Server..."
ssh -o StrictHostKeyChecking=no -J ubuntu@$APP_SERVER_IP ubuntu@$INFRA_SERVER_IP "sudo mkdir -p /opt/sigame && sudo chown ubuntu:ubuntu /opt/sigame"
scp -o ProxyJump=ubuntu@$APP_SERVER_IP -r $PROJECT_ROOT/* ubuntu@$INFRA_SERVER_IP:/opt/sigame/
scp -o ProxyJump=ubuntu@$APP_SERVER_IP .env.production ubuntu@$INFRA_SERVER_IP:/opt/sigame/

echo -e "${GREEN}✓ Files copied${NC}"

# Step 11: Setup Infrastructure Server
echo -e "${BLUE}Step 11: Setting up Infrastructure Server...${NC}"
ssh -J ubuntu@$APP_SERVER_IP ubuntu@$INFRA_SERVER_IP "sudo bash /opt/sigame/deployment/scripts/setup-server2.sh"
echo -e "${GREEN}✓ Infrastructure Server ready${NC}"

# Step 12: Setup Application Server
echo -e "${BLUE}Step 12: Setting up Application Server...${NC}"
ssh ubuntu@$APP_SERVER_IP "sudo bash /opt/sigame/deployment/scripts/setup-server1.sh"
echo -e "${GREEN}✓ Application Server ready${NC}"

# Step 13: Done!
echo ""
echo "=========================================="
echo -e "${GREEN}✓ Deployment Complete!${NC}"
echo "=========================================="
echo ""
terraform output connection_info
echo ""
echo "Credentials saved in: .env.production"
echo ""
echo "Next steps:"
echo "1. Test the application: http://$APP_SERVER_IP:3001"
echo "2. Setup SSL: ssh ubuntu@$APP_SERVER_IP 'sudo /opt/sigame/deployment/nginx/ssl-setup.sh'"
echo "3. Configure Grafana dashboards: http://$APP_SERVER_IP:3000"
echo ""
echo "=========================================="

